# Content Based Recommender System

In [165]:
import pandas as pd

In [166]:
df = pd.read_excel('MaiData.xlsx')
df.drop(columns = ['Runtime','IMDB','Language','Director','Actor','Actress','Year','Budget','BoxOffice','Review(5-best,4-Good,3-ontimewatch,2-worst,1-dontwatch)'], inplace = True)
df2 = df.copy()
for i in range(df.shape[0]):
    df['user'] = 'Gurudeep'
first_column = df.pop('user')
df.insert(0, 'user', first_column)
second_column = df.pop('MyRating')
df.insert(2, 'MyRating', second_column)
df.head(2)

user MovieName  MyRating  Family  Musical  Scifi  Adventure  Horror  \
0  Gurudeep   Vedalam       5.0       0        0      0          0       0   
1  Gurudeep     Raazi       8.0       0        0      0          0       0   

   Fantasy  War  Crime  Comedy  Romance  Drama  Thriller  Action  
0        0    0      0       0        1      0         0       1  
1        0    0      0       0        0      0         1       1

In [167]:
df1 = df
classes = list(df1.columns)[1:]
classes = classes[3:]
for cla in classes:
    df1[cla] = (df1[cla]*df1['MyRating'])
df1.head(3)

user   MovieName  MyRating  Family  Musical  Scifi  Adventure  Horror  \
0  Gurudeep     Vedalam       5.0       0      0.0    0.0        0.0     0.0   
1  Gurudeep       Raazi       8.0       0      0.0    0.0        0.0     0.0   
2  Gurudeep  Mr.Perfect      10.0       0      0.0    0.0        0.0     0.0   

   Fantasy  War  Crime  Comedy  Romance  Drama  Thriller  Action  
0      0.0  0.0    0.0     0.0      5.0    0.0       0.0     5.0  
1      0.0  0.0    0.0     0.0      0.0    0.0       8.0     8.0  
2      0.0  0.0    0.0    10.0     10.0   10.0       0.0     0.0

In [168]:
user_profiles = df1.drop('MyRating', axis = 1)
user_profiles = user_profiles.groupby(['user']).sum()
user_profiles["total"] = user_profiles[classes].sum(axis=1)
user_profiles

Family  Musical  Scifi  Adventure  Horror  Fantasy   War  Crime  \
user                                                                        
Gurudeep       5     26.0   24.0       41.0    10.0     39.0  18.0   19.0   

          Comedy  Romance  Drama  Thriller  Action  total  
user                                                       
Gurudeep    94.0    135.0  215.5      36.0   334.5  992.0

In [169]:
for cla in classes:
    user_profiles[cla] = (user_profiles[cla] / user_profiles["total"])
user_profiles = user_profiles.drop("total", axis=1)
user_profiles

Family  Musical     Scifi  Adventure    Horror   Fantasy       War  \
user                                                                           
Gurudeep       5  0.02621  0.024194   0.041331  0.010081  0.039315  0.018145   

             Crime    Comedy   Romance     Drama  Thriller    Action  
user                                                                  
Gurudeep  0.019153  0.094758  0.136089  0.217238   0.03629  0.337198

In [170]:
df.head(3)

user   MovieName  MyRating  Family  Musical  Scifi  Adventure  Horror  \
0  Gurudeep     Vedalam       5.0       0      0.0    0.0        0.0     0.0   
1  Gurudeep       Raazi       8.0       0      0.0    0.0        0.0     0.0   
2  Gurudeep  Mr.Perfect      10.0       0      0.0    0.0        0.0     0.0   

   Fantasy  War  Crime  Comedy  Romance  Drama  Thriller  Action  
0      0.0  0.0    0.0     0.0      5.0    0.0       0.0     5.0  
1      0.0  0.0    0.0     0.0      0.0    0.0       8.0     8.0  
2      0.0  0.0    0.0    10.0     10.0   10.0       0.0     0.0

In [171]:
df2

MovieName  Family  Musical  Scifi  Adventure  Horror  \
0                   Vedalam       0        0      0          0       0   
1                     Raazi       0        0      0          0       0   
2                Mr.Perfect       0        0      0          0       0   
3                   Akhanda       0        0      0          0       0   
4                        96       0        0      0          0       0   
..                      ...     ...      ...    ...        ...     ...   
63               Red Notice       0        0      0          0       0   
64         Ante Sundaraniki       0        0      0          0       0   
65                   Avatar       0        0      1          0       0   
66             Orey Bujjiga       0        0      0          0       0   
67  Uri The Surgical Strike       0        0      0          0       0   

    Fantasy  War  Crime  Comedy  Romance  Drama  Thriller  Action  MyRating  
0         0    0      0       0        1      0         0       1       5.0  
1         0    0      0       0        0      0         1       1       8.0  
2         0    0      0       1        1      1         0       0      10.0  
3         0    0      0       0        0      1         0       1       9.0  
4         0    0      0       0        1      1         0       0      10.0  
..      ...  ...    ...     ...      ...    ...       ...     ...       ...  
63        0    0      0       1        0      0         0       1       8.0  
64        0    0      0       1        1      0         0       1       8.0  
65        0    0      0       0        0      0         0       1      10.0  
66        0    0      0       1        1      1         0       0       8.0  
67        0    1      0       0        0      0         0       1       NaN  

[68 rows x 15 columns]

In [172]:
import numpy as np
categories_np =np.array(df2.drop(columns = ["MovieName","MyRating"], axis=1))
categories_np

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,

In [173]:
user_profiles_np = np.array(user_profiles)
user_profiles_np

array([[5.        , 0.02620968, 0.02419355, 0.04133065, 0.01008065,
        0.03931452, 0.01814516, 0.01915323, 0.09475806, 0.13608871,
        0.2172379 , 0.03629032, 0.33719758]])

In [174]:
preferences = np.dot(user_profiles_np, categories_np.T)
min_rating = 2
max_rating = 10
preferences = preferences * (max_rating - min_rating) + min_rating
preferences

array([[ 5.78629032,  4.98790323,  5.58467742,  6.43548387,  4.8266129 ,
         5.78629032,  4.98790323,  4.85080645,  6.43548387,  5.78629032,
         4.84274194,  6.43548387,  5.78629032,  4.8266129 ,  6.43548387,
         6.43548387,  6.43548387,  6.43548387,  5.78629032,  2.75806452,
         5.45564516,  6.43548387,  4.85080645,  2.39516129,  5.78629032,
         6.43548387,  5.78629032,  4.49596774,  4.98790323,  6.43548387,
         2.64516129,  4.98790323,  5.78629032,  6.43548387,  6.43548387,
         5.45564516,  5.78629032,  5.78629032,  4.49596774,  4.89112903,
         5.02822581,  6.43548387,  6.43548387,  4.89112903,  6.43548387,
         6.43548387,  6.43548387,  6.43548387,  4.49596774,  6.43548387,
         3.94758065,  2.64516129,  2.64516129,  2.64516129,  6.43548387,
         2.43548387, 43.08870968, 42.20967742, 42.20967742, 42.33064516,
         3.07258065, 42.33064516,  2.75806452,  5.45564516,  6.54435484,
         4.89112903,  5.58467742,  4.84274194]])

In [175]:
predictions = df[['user','MovieName','MyRating']]
predictions["predicted_rating"] = np.ravel(preferences)
predictions.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


user   MovieName  MyRating  predicted_rating
0  Gurudeep     Vedalam       5.0          5.786290
1  Gurudeep       Raazi       8.0          4.987903
2  Gurudeep  Mr.Perfect      10.0          5.584677
3  Gurudeep     Akhanda       9.0          6.435484
4  Gurudeep          96      10.0          4.826613

In [177]:
predictions["squared_error"] = (predictions["predicted_rating"] - predictions["MyRating"]) ** 2
predictions.head(2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


user MovieName  MyRating  predicted_rating  squared_error
0  Gurudeep   Vedalam       5.0          5.786290       0.618252
1  Gurudeep     Raazi       8.0          4.987903       9.072727

In [180]:
predictions["squared_error"].mean() ** .5    # High Error 

9.4893554089512

In [181]:
predictions.loc[predictions['MyRating'].isnull()].drop("MyRating", axis=1)

user                MovieName  predicted_rating  squared_error
67  Gurudeep  Uri The Surgical Strike          4.842742            NaN